### ISSUE TITLE
Error when trying to create first app "Hello World" to android

### ISSUE THREAD

**Issue by lpirola** [hypermurea/generator-phonegap#1]
Hello,

i installed your generator and after that i tried to ran. Then, provide must have information to create the project and the following exception was throw:

```
/usr/local/lib/node_modules/generator-phonegap/node_modules/extended-fs/src/fs.js:417
            throw new TypeError(src + ' does not exist');
                  ^
TypeError: /private/tmp/generator/phonegap/www/res does not exist
    at Object.fsExtended.copyDirSync (/usr/local/lib/node_modules/generator-phonegap/node_modules/extended-fs/src/fs.js:417:19)
    at PhonegapGenerator.phonegapSetup (/usr/local/lib/node_modules/generator-phonegap/app/index.js:193:8)
    at /usr/local/lib/node_modules/generator-phonegap/node_modules/yeoman-generator/lib/base.js:290:20
    at /usr/local/lib/node_modules/generator-phonegap/node_modules/yeoman-generator/node_modules/async/lib/async.js:548:21
    at /usr/local/lib/node_modules/generator-phonegap/node_modules/yeoman-generator/node_modules/async/lib/async.js:224:13
    at iterate (/usr/local/lib/node_modules/generator-phonegap/node_modules/yeoman-generator/node_modules/async/lib/async.js:131:13)
    at /usr/local/lib/node_modules/generator-phonegap/node_modules/yeoman-generator/node_modules/async/lib/async.js:142:25
    at /usr/local/lib/node_modules/generator-phonegap/node_modules/yeoman-generator/node_modules/async/lib/async.js:226:17
    at /usr/local/lib/node_modules/generator-phonegap/node_modules/yeoman-generator/node_modules/async/lib/async.js:553:34
    at /usr/local/lib/node_modules/generator-phonegap/node_modules/yeoman-generator/lib/base.js:278:11
```

I would be glad if you could help me.

yo version: 1.0.4
so version: macos 10.8.5

Thanks!

**Comment by joperron** [comment]
Getting the same error

**Comment by joperron** [comment]
you should close this

**Comment by juicef** [comment]
This is still an open issue. I just got the same problem. Created the folders manually though, both res and img folder. Now it works. Hope this helps someone ;)

**Comment by hypermurea** [comment]
resolved
