### ISSUE TITLE
Unable to Install

### ISSUE THREAD

**Issue by mukundha** [hypermurea/generator-phonegap#12]
I get this error during install,

222 verbose stack Valid install targets:
222 verbose stack ["3.5.0-0.19.23","0.2.0","0.2.1","0.2.2","0.3.0","0.4.0","0.4.1","0.5.0","0.6.0","0.6.1","0.7.0","0.7.1","0.7.2","0.7.3","0.7.4","0.7.5","0.7.6","0.7.7","0.7.8","0.8.0","0.8.1","0.9.0","0.9.1","0.9.2","0.9.3","0.9.4","2.8.0-0.10.0","2.8.0-0.10.1","2.8.0-0.10.2","2.8.0-0.10.3","2.8.0-0.10.4","2.8.0-0.10.6","2.8.1-0.11.0","2.9.0-0.12.2","2.9.0-0.12.3","2.9.0-0.12.4","2.9.0-0.12.5","2.9.0-0.12.6","2.9.0-0.12.7","2.9.0-0.12.8","2.9.0-rc1-0.12.0","2.9.0-rc1-0.12.1","2.9.0-rc1-0.12.2","2.9.0-0.12.9","2.9.0-0.12.10","2.9.0-0.12.11","2.9.0-0.13.0","2.9.0-0.13.1","2.9.0-0.13.2","3.0.0-rc1-0.13.2","3.0.0-rc1-0.13.3","3.0.0-0.14.0","3.0.0-0.14.1","3.0.0-0.14.2","3.0.0-0.14.3","3.0.0-0.14.4","3.1.0-0.15.0","3.2.0-0.15.0","3.2.0-0.16.0","3.2.0-0.17.0","3.2.0-0.17.1","3.3.0-0.17.1","3.3.0-0.18.0","3.3.0-0.18.1","3.3.0-0.19.0","3.3.0-0.19.1","3.3.0-0.19.2","3.3.0-0.19.3","3.3.0-0.19.4","3.3.0-0.19.5","3.3.0-0.19.6","3.4.0-0.19.7","3.4.0-0.19.8","3.4.0-0.19.9","3.4.0-0.19.10","3.4.0-0.19.11","3.4.0-0.19.12","3.4.0-0.19.13","3.4.0-0.19.14","3.4.0-0.19.15","3.4.0-0.19.16","3.4.0-0.19.17","3.4.0-0.19.18","3.4.0-0.19.19","3.4.0-0.19.20","3.4.0-0.19.21","3.4.0-0.20.0","3.5.0-0.19.23","3.5.0-0.20.0","3.5.0-0.20.1","3.5.0-0.20.3","3.5.0-0.20.4","3.5.0-0.20.5","3.5.0-0.20.6","3.5.0-0.20.7","3.5.0-0.20.9","3.5.0-0.20.10","3.5.0-0.20.14","3.5.0-0.21.14","3.5.0-0.21.15","3.5.0-0.21.16","3.5.0-0.21.17","3.5.0-0.21.18","3.6.0-0.21.18","3.6.0-0.21.19","3.6.3-0.22.0","3.6.3-0.22.1","3.6.3-0.22.2","3.6.3-0.22.3","3.6.3-0.22.4","3.6.3-0.22.5","3.6.3-0.22.6","3.6.3-0.22.7","4.0.0-0.22.7","4.1.2-0.22.7","4.1.2-0.22.8","4.1.2-0.22.9","4.1.2-0.22.10","4.1.2-0.22.11","4.1.2-0.22.12","4.2.0-0.23.0","4.2.0-0.24.0","4.2.0-0.24.1","4.2.0-0.24.2","4.2.0-0.25.0","4.2.0-0.26.0","5.0.0-0.27.0","5.0.0-0.27.1","5.0.0-0.28.0","5.0.0-0.28.1","5.1.1-0.29.0","5.1.1","5.2.0","5.2.1","5.2.2","5.2.3","5.3.1"]
222 verbose stack
222 verbose stack     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:260:12)
222 verbose stack     at next (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:239:17)
222 verbose stack     at setData (/usr/local/lib/node_modules/npm/lib/cache/add-named.js:216:5)
222 verbose stack     at RES (/usr/local/lib/node_modules/npm/node_modules/inflight/inflight.js:23:14)
222 verbose stack     at f (/usr/local/lib/node_modules/npm/node_modules/once/once.js:16:25)
222 verbose stack     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:167:7)
222 verbose stack     at Object.oncomplete (fs.js:107:15)

I have phonegap 3.5, is it not supported?

**Comment by Chris2011** [comment]
Have the same problem on windows 7, have Phonegap 5.3.9. Did you find a solution?
